health: add missing links to libpng and libbase
* fixes linking issue
 bootable/recovery/minui/resources.cpp:235: error: undefined reference to 'png_destroy_read_struct'
 bootable/recovery/minui/resources.cpp:227: error: undefined reference to 'png_read_row'
 bootable/recovery/minui/resources.cpp:235: error: undefined reference to 'png_destroy_read_struct'
 bootable/recovery/minui/resources.cpp:71: error: undefined reference to 'png_sig_cmp'
 bootable/recovery/minui/resources.cpp:125: error: undefined reference to 'png_destroy_read_struct'
 bootable/recovery/minui/resources.cpp:125: error: undefined reference to 'png_destroy_read_struct'
 bootable/recovery/minui/resources.cpp:76: error: undefined reference to 'png_create_read_struct'
 bootable/recovery/minui/resources.cpp:82: error: undefined reference to 'png_create_info_struct'
 bootable/recovery/minui/resources.cpp:88: error: undefined reference to 'png_set_longjmp_fn'

Change-Id: I711e60188a6aefe1ba285c9cba1c4163f2ec4148